### ISSUE TITLE
The method 'BindingWidget' isn't defined for the class '_HomePageViewState'

### ISSUE THREAD

**Issue by pishguy** [Bowman74/fmvvm#10] opened 2019-06-04 16:44 UTC
for this simple implementation code with this library i get this error:

> error: The method 'BindingWidget' isn't defined for the class '_HomePageViewState'. (undefined_method at [flutter_fmvvm] lib\main.dart:64)
> 
> error: The argument type '_HomePageViewModel' can't be assigned to the parameter type 'PropertyInfo'. (argument_type_not_assignable at [flutter_fmvvm] lib\main.dart:65)
> 
> error: The argument type 'String' can't be assigned to the parameter type 'BindableBase'. (argument_type_not_assignable at [flutter_fmvvm] lib\main.dart:65)
> 
> error: Too many positional arguments: 2 expected, but 3 found. (extra_positional_arguments at [flutter_fmvvm] lib\main.dart:65)

how can i resolve that?

**I THINK LATEST PACKAGE DONT UPDATED IN REPOSITORY, BECAUSE WITH SOURCE OF LIBRARY I DONT HAVE ANY PROBLEM**

**pubspec.yaml:**

> dependencies:
>   flutter:
>     sdk: flutter
> 
>   cupertino_icons: ^0.1.2
>   fmvvm: ^0.8.2
> dev_dependencies:
>   flutter_test:
>     sdk: flutter

```
import 'package:flutter/material.dart';

import 'package:fmvvm/bindings/bindings.dart';
import 'package:fmvvm/fmvvm.dart';

void main() => runApp(MyApp());

class MyApp extends FmvvmApp {
  @override
  registerComponents(ComponentResolver componentResolver) {
    componentResolver.registerType<_HomePageViewModel>(() {
      return _HomePageViewModel(
          componentResolver.resolveType<NavigationService>());
    });
  }

  @override
  String getInitialRoute() {
    return 'my_app';
  }

  @override
  Route getRoutes(RouteSettings settings) {
    if (settings.name == 'my_app') {
      var arguments = settings.arguments ??
          Core.componentResolver
              .resolveType<NavigationService>()
              .createViewModel<_HomePageViewModel>(null);
      return buildRoute(settings, _HomePageView(arguments));
    }
  }

  @override
  String getTitle() {
    return 'practice FMVVM';
  }
}

class _HomePageView extends FmvvmStatefulWidget<_HomePageViewModel> {
  final String title;

  _HomePageView(ViewModel viewModel, {Key key, this.title})
      : super(viewModel, key: key);

  @override
  _HomePageViewState createState() => _HomePageViewState(bindableBase);
}

class _HomePageViewState extends FmvvmState<_HomePageView, _HomePageViewModel> {
  @override
  _HomePageViewState(_HomePageViewModel viewModel) : super(viewModel, true);

  Widget build(BuildContext context) {
    super.build(context);
    return Scaffold(
      appBar: AppBar(
        title: Text('sample'),
      ),
      body: Column(
        children: <Widget>[
          Container(
            child: Text('aaa'),
          ),
          BindingWidget<_HomePageViewModel>(bindings: <Binding>[
            Binding('counter', bindableBase, _HomePageViewModel.counterProperty,
                bindingDirection: BindingDirection.OneTime,
                valueConverter: _NumberConverter())
          ]),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: bindableBase.incrementCounter.execute,
        child: Icon(Icons.add),
      ),
    );
  }
}

class _HomePageViewModel extends ViewModel {
  NavigationService _navigationService;

  @override
  _HomePageViewModel(this._navigationService);

  static PropertyInfo counterProperty = PropertyInfo('count', int);

  int get counter => getValue(counterProperty);

  set counter(int value) => setValue(counterProperty, value);
  Command _incrementCounter;

  Command get incrementCounter {
    _incrementCounter ??= Command(() {
      counter++;
    });
    return _incrementCounter;
  }
}

```

**Comment by Bowman74** [comment] 2019-06-04 19:27
Yes, it looks like you had a older version of the code. the problem is probably my documentation uses the line:

```fmvvm: ^0.8.2```

I am updating the documentation to:

```fmvvm: ^0.9.3```

Thank you. Closing this bug.

**Closed as completed by Bowman74** 2019-06-04 19:27 UTC
Labels: question
